export const menuData = {
  hotCoffees: [
    {
      id: "01",
      nameEn: "Cafe Americano",
      nameAr: "قهوة أمريكانو",
      descriptionEn: "Espresso shots topped with hot water",
      descriptionAr: "جرعات إسبريسو مغطاة بالماء الساخن",
      imgUrl: "/images/ourmenu/Hot Drinks/cafe-americano.jpg",
      link: "/store",
    },
    {
      id: "02",
      nameEn: "Cappuccino",
      nameAr: "كابتشينو",
      descriptionEn: "Dark espresso lies in wait under milk foam",
      descriptionAr: "الإسبريسو الداكن يختبئ تحت رغوة الحليب",
      imgUrl: "/images/ourmenu/Hot Drinks/cappuccino.jpg",
      link: "/store",
    },
    {
      id: "03",
      nameEn: "Espresso",
      nameAr: "إسبريسو",
      descriptionEn: "Signature Espresso Roast with rich flavor",
      descriptionAr: "تحميص إسبريسو المميز بنكهة غنية",
      imgUrl: "/images/ourmenu/Hot Drinks/espresso.jpg",
      typeEn: "Classic",
      typeAr: "كلاسيكي",
      link: "/store",
    },
    {
      id: "04",
      nameEn: "Caramel Macchiato",
      nameAr: "كاراميل ماكياتو",
      descriptionEn: "Freshly steamed milk with vanilla-flavored syrup",
      descriptionAr: "حليب بخار طازج مع شراب بنكهة الفانيليا",
      imgUrl: "/images/ourmenu/Hot Drinks/caramel-macchiato.jpg",
      link: "/store",
    },
    {
      id: "05",
      nameEn: "Caffee Mocha",
      nameAr: "قهوة موكا",
      descriptionEn: "Full-bodied espresso combined with mocha",
      descriptionAr: "إسبريسو غني ممزوج بالموكّا",
      imgUrl: "/images/ourmenu/Hot Drinks/caffee-mocha.jpg",
      link: "/store",
    },
  ],

  coldCoffees: [
    {
      id: "06",
      nameEn: "Iced Coffee with Milk",
      nameAr: "قهوة مثلجة مع حليب",
      descriptionEn: "Iced Coffee Blend with milk served chilled",
      descriptionAr: "خلطة قهوة مثلجة مع حليب تُقدّم باردة",
      imgUrl: "/images/ourmenu/Iced Coffee/ice-coffee.jpg",
      link: "/store",
    },
    {
      id: "07",
      nameEn: "Iced Espresso",
      nameAr: "إسبريسو مثلج",
      descriptionEn: "Smooth signature Espresso Roast over ice boasts",
      descriptionAr: "تحميص إسبريسو المميز الناعم على الثلج يقدّم",
      imgUrl: "/images/ourmenu/Iced Coffee/iced-espresso.jpg",
      link: "/store",
    },
    {
      id: "08",
      nameEn: "Iced Caramel Macchiato",
      nameAr: "كاراميل ماكياتو مثلج",
      descriptionEn: "Signature caramel crosshatch and a mocha drizzle",
      descriptionAr: "تشكيلة الكراميل المميزة بلمسة تقاطيع وقطرات الموكّا",
      imgUrl: "/images/ourmenu/Iced Coffee/ice caramel machiatto.png",
      link: "/store",
    },
    {
      id: "09",
      nameEn: "Flat Milk",
      nameAr: "حليب خالي من الرغوة",
      descriptionEn: "Fresh brewed coffee and steamed milk",
      descriptionAr: "قهوة مخمرة حديثًا وحليب بخار",
      imgUrl: "/images/ourmenu/Iced Coffee/ice shaken.png",
      typeEn: "Barista Recommended",
      typeAr: "موصى به من قبل الباريستا",
      link: "/store",
    },
    {
      id: "010",
      nameEn: "Iced Latte",
      nameAr: "لاتيه مثلج",
      descriptionEn: "Signature espresso are intentionally combined over ice",
      descriptionAr: "الإسبريسو المميز يُمزج عمدًا فوق الثلج",
      imgUrl: "/images/ourmenu/Iced Coffee/ice latte.png",
      link: "/store",
    },
  ],

  Bakery: [
    {
      id: "110",
      nameEn: "Butter Croissant",
      nameAr: "كرواسون الزبدة",
      descriptionEn: "Classic croissant is made with real butter",
      descriptionAr: "الكرواسون الكلاسيكي يُصنع من زبدة حقيقية",
      imgUrl: "/images/ourmenu/Desserts & Bakery/d.jpg",
      link: "/store",
    },
    {
      id: "111",
      nameEn: "Chocolate Brownie",
      nameAr: "براونيز الشوكولاتة",
      descriptionEn: "Rich chocolate brownie with chunks of chocolate",
      descriptionAr: "براونيز الشوكولاتة الغنية مع قطع الشوكولاتة",
      imgUrl: "/images/ourmenu/Desserts & Bakery/Chocolate Chip Cookies.png",
      link: "/store",
    },
    {
      id: "110",
      nameEn: "Blueberry Scone",
      nameAr: "سكون التوت الأزرق",
      descriptionEn: "A traditional scone with blueberries, buttermilk",
      descriptionAr: "سكون تقليدي مع التوت الأزرق والحليب الرائب",
      imgUrl: "/images/ourmenu/Desserts & Bakery/Muffin Blueberry.png",
      link: "/store",
    },
  ],

  Lunch: [
    {
      id: "222",
      nameEn: "Chicken Sandwitches",
      nameAr: "سندويشات دجاج",
      descriptionEn: "White-meat chicken, veggie slaw, cucumber, cilantro",
      descriptionAr: "دجاج لحم أبيض، سلطة خضروات، خيار، كزبرة",
      imgUrl: "/images/ourmenu/Sandwiches/sandwishes.png",
      link: "/store",
    },
    {
      id: "223",
      nameEn: "Lunch Box",
      nameAr: "علبة غداء",
      descriptionEn:
        "Tender and juicy sous vide grilled chicken breast paired with roasted red pepper",
      descriptionAr:
        "صدر دجاج مشوي بطريقت السوس فيد، طري وعصير، مع فلفل أحمر محمص",
      imgUrl: "/images/ourmenu/Sandwiches/lunch.jpg",
      link: "/store",
    },
    {
      id: "224",
      nameEn: "Chicken Wrap",
      nameAr: "لفائف الدجاج",
      descriptionEn:
        "Grilled white chicken, peanut-coconut sauce, chile-lime slaw and ginger cream cheese",
      descriptionAr:
        "دجاج أبيض مشوي، صلصة الفول السوداني وجوز الهند، سلطة تشيلي والليمون، وجبنة كريمية بالزنجبيل",
      imgUrl: "/images/ourmenu/Sandwiches/TURKEY CHEESE CIABATTA SANDWICH.png",
      link: "/store",
    },
  ],
}
